### ISSUE TITLE
Unable to Open Activity in Web Browser in App

### ISSUE THREAD

**Issue by SeanCooke** [cromat/TomTom-Sports-Connect-Ubuntu-20.04-Mint-20-#1]
![cannot-open-tomtom-sports-in-firefox](https://user-images.githubusercontent.com/7542731/100526106-ed880500-3193-11eb-9e87-a27bdac276f3.png)
Hello - thank you so much for writing these instructions!  They helped me fix the "We could not connect to your watch" issue :smile:

Because we are now running `/usr/local/TomTomSportsConnect/bin/TomTomSportsConnect` as root, I am having trouble opening my activities in a my default web browser (Firefox) by clicking the "TomTom Sports" link on the "READY TO GO" screen in the app.  I am running Ubuntu 20.04

It looks like this is because we cannot run Firefox as root in a regular user's session.  Do you have any suggestions on how to fix this?  Below is my terminal output when I attempt to click the "TomTom Sports" link on the "READY TO GO" screen in the app.  Thank you again!

```bash
(base) scooke@scooke-lenovo:~$ sudo /usr/local/TomTomSportsConnect/bin/TomTomSportsConnect

WARNING: This project is using the experimental QML API extensions for QtWebKit and is therefore tied to a specific QtWebKit release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by scooke.)
[5583:5583:1128/122334.513072:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by scooke.)
/usr/bin/xdg-open: 869: iceweasel: not found
/usr/bin/xdg-open: 869: seamonkey: not found
/usr/bin/xdg-open: 869: mozilla: not found
/usr/bin/xdg-open: 869: epiphany: not found
/usr/bin/xdg-open: 869: konqueror: not found
/usr/bin/xdg-open: 869: chromium: not found
/usr/bin/xdg-open: 869: chromium-browser: not found
[5613:5613:1128/122334.571155:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'https://mysports.tomtom.com/app/activity?locale=en_us&muid=HN6475G04960'
^C
```

**Comment by cromat** [comment]
@SeanCooke Yes, the problem is that you are running now firefox as root if  you click "TomTom Sports" link. The workaround is just to open firefox from OS as regular user and go to [https://mysports.tomtom.com](https://mysports.tomtom.com) manually. You will see all your latest activities normally as they will be synced.
